/**
 * Hardcoded seed list of GitHub users used by the autocomplete feature
 * during local development (when GitHub OAuth is disabled). Generated
 * from the public membership of the tc39 organisation, with display
 * names and companies enriched via batched GraphQL `user(login:)` queries;
 * refresh by re-running scripts/refresh-dev-users.mjs.
 */

export interface DevUser {
  ghid: number;
  login: string;
  name: string;
  organisation?: string;
  avatarUrl: string;
}

export const DEV_USERS: readonly DevUser[] = [
  {
    ghid: 18689448,
    login: 'AbhiPrasad',
    name: 'Abhijeet Prasad',
    organisation: '@braintrustdata',
    avatarUrl: 'https://avatars.githubusercontent.com/u/18689448?v=4',
  },
  {
    ghid: 316498,
    login: 'akira-cn',
    name: 'Yvo',
    organisation: 'AirCode',
    avatarUrl: 'https://avatars.githubusercontent.com/u/316498?v=4',
  },
  {
    ghid: 5139846,
    login: 'alessbell',
    name: 'Alessia Bellisario',
    organisation: 'Netflix',
    avatarUrl: 'https://avatars.githubusercontent.com/u/5139846?v=4',
  },
  {
    ghid: 505435,
    login: 'allenwb',
    name: 'Allen Wirfs-Brock',
    organisation: 'Wirfs-Brock Associates',
    avatarUrl: 'https://avatars.githubusercontent.com/u/505435?v=4',
  },
  {
    ghid: 8225977,
    login: 'andreubotella',
    name: 'Andreu Botella',
    organisation: '@Igalia',
    avatarUrl: 'https://avatars.githubusercontent.com/u/8225977?v=4',
  },
  {
    ghid: 721038,
    login: 'andyfleming',
    name: 'Andy Fleming',
    avatarUrl: 'https://avatars.githubusercontent.com/u/721038?v=4',
  },
  {
    ghid: 1544111,
    login: 'annevk',
    name: 'Anne van Kesteren',
    organisation: '@apple',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1544111?v=4',
  },
  {
    ghid: 1935246,
    login: 'anonrig',
    name: 'Yagiz Nizipli',
    organisation: 'xAI',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1935246?v=4',
  },
  {
    ghid: 11247099,
    login: 'antfu',
    name: 'Anthony Fu',
    organisation: '@vercel team @nuxt',
    avatarUrl: 'https://avatars.githubusercontent.com/u/11247099?v=4',
  },
  {
    ghid: 45845,
    login: 'arv',
    name: 'Erik Arvidsson',
    organisation: '@rocicorp',
    avatarUrl: 'https://avatars.githubusercontent.com/u/45845?v=4',
  },
  {
    ghid: 1163554,
    login: 'ashleygwilliams',
    name: 'ashley williams',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1163554?v=4',
  },
  {
    ghid: 6061509,
    login: 'atikenny',
    name: 'Attila Bartha',
    avatarUrl: 'https://avatars.githubusercontent.com/u/6061509?v=4',
  },
  {
    ghid: 1653598,
    login: 'bakkot',
    name: 'Kevin Gibbons',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1653598?v=4',
  },
  {
    ghid: 11073,
    login: 'banterability',
    name: 'Jeff Long',
    avatarUrl: 'https://avatars.githubusercontent.com/u/11073?v=4',
  },
  {
    ghid: 485321,
    login: 'bashor',
    name: 'Zalim Bashorov',
    organisation: '@JetBrains',
    avatarUrl: 'https://avatars.githubusercontent.com/u/485321?v=4',
  },
  {
    ghid: 5750,
    login: 'benjamn',
    name: 'Ben Newman',
    organisation: 'Apollo Graph, Inc (formerly: Meteor, Facebook/Instagram, Quora, Mozilla)',
    avatarUrl: 'https://avatars.githubusercontent.com/u/5750?v=4',
  },
  {
    ghid: 8297234,
    login: 'BethGriggs',
    name: 'Beth Griggs',
    organisation: 'IBM',
    avatarUrl: 'https://avatars.githubusercontent.com/u/8297234?v=4',
  },
  {
    ghid: 234659,
    login: 'bmeck',
    name: 'Bradley Farias',
    avatarUrl: 'https://avatars.githubusercontent.com/u/234659?v=4',
  },
  {
    ghid: 502396,
    login: 'bnb',
    name: 'Tierney Cyren',
    avatarUrl: 'https://avatars.githubusercontent.com/u/502396?v=4',
  },
  {
    ghid: 122117,
    login: 'boazsender',
    name: 'boazsender',
    avatarUrl: 'https://avatars.githubusercontent.com/u/122117?v=4',
  },
  {
    ghid: 924465,
    login: 'boneskull',
    name: 'Christopher Hiller',
    avatarUrl: 'https://avatars.githubusercontent.com/u/924465?v=4',
  },
  {
    ghid: 1430279,
    login: 'Boshen',
    name: 'Boshen',
    organisation: '@voidzero-dev @oxc-project @rolldown',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1430279?v=4',
  },
  {
    ghid: 4448075,
    login: 'brad-decker',
    name: 'Brad Decker',
    organisation: '@ConciergeAuctions',
    avatarUrl: 'https://avatars.githubusercontent.com/u/4448075?v=4',
  },
  {
    ghid: 8822573,
    login: 'BridgeAR',
    name: 'Ruben Bridgewater',
    organisation: 'Datadog, Inc.',
    avatarUrl: 'https://avatars.githubusercontent.com/u/8822573?v=4',
  },
  {
    ghid: 856935,
    login: 'brittanydionigi',
    name: 'Brittany Dionigi',
    organisation: 'google',
    avatarUrl: 'https://avatars.githubusercontent.com/u/856935?v=4',
  },
  {
    ghid: 11236,
    login: 'bterlson',
    name: 'Brian Terlson',
    organisation: '@Microsoft',
    avatarUrl: 'https://avatars.githubusercontent.com/u/11236?v=4',
  },
  {
    ghid: 19228318,
    login: 'CanadaHonk',
    name: 'Oliver Medhurst',
    organisation: 'Porffor',
    avatarUrl: 'https://avatars.githubusercontent.com/u/19228318?v=4',
  },
  {
    ghid: 1507086,
    login: 'chicoxyzzy',
    name: 'Sergey Rubanov',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1507086?v=4',
  },
  {
    ghid: 88485,
    login: 'cncuckoo',
    name: 'Songfeng Li（李松峰）',
    organisation: 'ByteDance',
    avatarUrl: 'https://avatars.githubusercontent.com/u/88485?v=4',
  },
  {
    ghid: 2036040,
    login: 'codebytere',
    name: 'Shelley Vohr',
    organisation: '@microsoft',
    avatarUrl: 'https://avatars.githubusercontent.com/u/2036040?v=4',
  },
  {
    ghid: 9023,
    login: 'Constellation',
    name: 'Yusuke Suzuki',
    organisation: '@apple',
    avatarUrl: 'https://avatars.githubusercontent.com/u/9023?v=4',
  },
  {
    ghid: 15326526,
    login: 'ctcpip',
    name: 'Chris de Almeida',
    organisation: '@IBM',
    avatarUrl: 'https://avatars.githubusercontent.com/u/15326526?v=4',
  },
  {
    ghid: 972891,
    login: 'DanielRosenwasser',
    name: 'Daniel Rosenwasser',
    organisation: '@Microsoft',
    avatarUrl: 'https://avatars.githubusercontent.com/u/972891?v=4',
  },
  { ghid: 55392, login: 'davethegr8', name: 'Dave', avatarUrl: 'https://avatars.githubusercontent.com/u/55392?v=4' },
  {
    ghid: 381179,
    login: 'davidsonfellipe',
    name: 'Davidson Fellipe',
    organisation: '@upgrade',
    avatarUrl: 'https://avatars.githubusercontent.com/u/381179?v=4',
  },
  {
    ghid: 4356609,
    login: 'dcrousso',
    name: 'Devin Rousso',
    avatarUrl: 'https://avatars.githubusercontent.com/u/4356609?v=4',
  },
  {
    ghid: 21011599,
    login: 'decompil3d',
    name: 'Jonathan Keslin',
    organisation: 'Atlassian',
    avatarUrl: 'https://avatars.githubusercontent.com/u/21011599?v=4',
  },
  {
    ghid: 5952481,
    login: 'devsnek',
    name: 'snek',
    organisation: '@WebAssembly @denoland @nodejs @tc39 @OpenJS-Foundation',
    avatarUrl: 'https://avatars.githubusercontent.com/u/5952481?v=4',
  },
  {
    ghid: 307871,
    login: 'dherman',
    name: 'Dave Herman',
    organisation: 'LinkedIn',
    avatarUrl: 'https://avatars.githubusercontent.com/u/307871?v=4',
  },
  {
    ghid: 1176744,
    login: 'diervo',
    name: 'Diego Ferreiro Val',
    organisation: '@trebellar',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1176744?v=4',
  },
  { ghid: 2362, login: 'disnet', name: 'Tim Disney', avatarUrl: 'https://avatars.githubusercontent.com/u/2362?v=4' },
  {
    ghid: 617481,
    login: 'domenic',
    name: 'Domenic Denicola',
    avatarUrl: 'https://avatars.githubusercontent.com/u/617481?v=4',
  },
  {
    ghid: 9669289,
    login: 'domfarolino',
    name: 'Dominic Farolino',
    organisation: 'Google',
    avatarUrl: 'https://avatars.githubusercontent.com/u/9669289?v=4',
  },
  {
    ghid: 2447456,
    login: 'dusave',
    name: 'Dustin Savery',
    organisation: '@github, @primer, Former  @painted-pixels, @nvidia, @lyft, @godaddy',
    avatarUrl: 'https://avatars.githubusercontent.com/u/2447456?v=4',
  },
  {
    ghid: 1290788,
    login: 'dveditz',
    name: 'Daniel Veditz',
    organisation: '@mozilla',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1290788?v=4',
  },
  {
    ghid: 617000,
    login: 'eemeli',
    name: 'Eemeli Aro',
    organisation: '@mozilla',
    avatarUrl: 'https://avatars.githubusercontent.com/u/617000?v=4',
  },
  {
    ghid: 46995,
    login: 'eligrey',
    name: 'Eli Grey',
    organisation: '@transcend-io',
    avatarUrl: 'https://avatars.githubusercontent.com/u/46995?v=4',
  },
  {
    ghid: 29096,
    login: 'ericf',
    name: 'Eric Ferraiuolo',
    organisation: 'Apple',
    avatarUrl: 'https://avatars.githubusercontent.com/u/29096?v=4',
  },
  {
    ghid: 16735925,
    login: 'evenstensberg',
    name: 'Even Stensberg',
    avatarUrl: 'https://avatars.githubusercontent.com/u/16735925?v=4',
  },
  {
    ghid: 1465795,
    login: 'fabalbon',
    name: 'Felipe Balbontín',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1465795?v=4',
  },
  {
    ghid: 1686833,
    login: 'fabiorocha',
    name: 'Fabio Rocha',
    organisation: 'Microsoft',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1686833?v=4',
  },
  {
    ghid: 59409,
    login: 'federicobucchi',
    name: 'Federico Bucchi',
    organisation: 'Apple',
    avatarUrl: 'https://avatars.githubusercontent.com/u/59409?v=4',
  },
  {
    ghid: 101553,
    login: 'fhinkel',
    name: 'F. Hinkelmann',
    organisation: 'Google',
    avatarUrl: 'https://avatars.githubusercontent.com/u/101553?v=4',
  },
  {
    ghid: 2368856,
    login: 'fniephaus',
    name: 'Fabio Niephaus',
    organisation: '@oracle',
    avatarUrl: 'https://avatars.githubusercontent.com/u/2368856?v=4',
  },
  {
    ghid: 782056,
    login: 'gesa',
    name: 'Aki',
    organisation: '@Expert-Zebra',
    avatarUrl: 'https://avatars.githubusercontent.com/u/782056?v=4',
  },
  {
    ghid: 224782,
    login: 'ghermeto',
    name: 'Guilherme Hermeto',
    organisation: 'Netflix',
    avatarUrl: 'https://avatars.githubusercontent.com/u/224782?v=4',
  },
  {
    ghid: 15943089,
    login: 'gibfahn',
    name: 'Gibson Fahnestock',
    avatarUrl: 'https://avatars.githubusercontent.com/u/15943089?v=4',
  },
  {
    ghid: 1199584,
    login: 'gibson042',
    name: 'Richard Gibson',
    organisation: 'Agoric',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1199584?v=4',
  },
  {
    ghid: 641505,
    login: 'gisenberg',
    name: 'Gabriel Isenberg',
    organisation: 'Riot Games',
    avatarUrl: 'https://avatars.githubusercontent.com/u/641505?v=4',
  },
  {
    ghid: 12926423,
    login: 'goyakin',
    name: 'Gorkem Yakin',
    avatarUrl: 'https://avatars.githubusercontent.com/u/12926423?v=4',
  },
  {
    ghid: 1246157,
    login: 'gramidt',
    name: 'Granville Schmidt',
    organisation: '@strata-io',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1246157?v=4',
  },
  {
    ghid: 1588648,
    login: 'gregtatum',
    name: 'Greg Tatum',
    organisation: 'Mozilla',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1588648?v=4',
  },
  {
    ghid: 565765,
    login: 'gsathya',
    name: 'Sathya Gunasekaran',
    organisation: '@facebook',
    avatarUrl: 'https://avatars.githubusercontent.com/u/565765?v=4',
  },
  { ghid: 159840, login: 'hax', name: 'HE Shi-Jun', avatarUrl: 'https://avatars.githubusercontent.com/u/159840?v=4' },
  {
    ghid: 18315,
    login: 'hemanth',
    name: 'Hemanth HM',
    organisation: '@paypal',
    avatarUrl: 'https://avatars.githubusercontent.com/u/18315?v=4',
  },
  {
    ghid: 14026360,
    login: 'himself65',
    name: 'Alex Yang',
    organisation: '@fundamental-bottom',
    avatarUrl: 'https://avatars.githubusercontent.com/u/14026360?v=4',
  },
  {
    ghid: 478856,
    login: 'hsivonen',
    name: 'Henri Sivonen',
    organisation: '@mozilla',
    avatarUrl: 'https://avatars.githubusercontent.com/u/478856?v=4',
  },
  {
    ghid: 5563315,
    login: 'Huxpro',
    name: 'Xuan Huang (黄玄)',
    organisation: '[ByteDance, Meta, ...China]',
    avatarUrl: 'https://avatars.githubusercontent.com/u/5563315?v=4',
  },
  {
    ghid: 983798,
    login: 'iarna',
    name: 'Rebecca Turner',
    avatarUrl: 'https://avatars.githubusercontent.com/u/983798?v=4',
  },
  {
    ghid: 4505008,
    login: 'ilias-t',
    name: 'Ilias',
    organisation: '@clavataai',
    avatarUrl: 'https://avatars.githubusercontent.com/u/4505008?v=4',
  },
  {
    ghid: 4624,
    login: 'indexzero',
    name: 'Charlie Robbins',
    avatarUrl: 'https://avatars.githubusercontent.com/u/4624?v=4',
  },
  {
    ghid: 1379244,
    login: 'isaacdurazo',
    name: 'Isaac Durazo',
    organisation: '@Doximity',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1379244?v=4',
  },
  {
    ghid: 5390719,
    login: 'Jack-Works',
    name: 'Jack Works',
    avatarUrl: 'https://avatars.githubusercontent.com/u/5390719?v=4',
  },
  {
    ghid: 49928364,
    login: 'jackbsteinberg',
    name: 'Jack Steinberg',
    avatarUrl: 'https://avatars.githubusercontent.com/u/49928364?v=4',
  },
  {
    ghid: 3012099,
    login: 'JakobJingleheimer',
    name: 'Jacob Smith',
    avatarUrl: 'https://avatars.githubusercontent.com/u/3012099?v=4',
  },
  {
    ghid: 952783,
    login: 'jamiebuilds',
    name: 'Jamie Kyle',
    organisation: '@signalapp',
    avatarUrl: 'https://avatars.githubusercontent.com/u/952783?v=4',
  },
  {
    ghid: 936006,
    login: 'jasonwilliams',
    name: 'Jason Williams',
    organisation: '@Bloomberg',
    avatarUrl: 'https://avatars.githubusercontent.com/u/936006?v=4',
  },
  {
    ghid: 4303,
    login: 'jdalton',
    name: 'John-David Dalton',
    organisation: 'Socket.dev',
    avatarUrl: 'https://avatars.githubusercontent.com/u/4303?v=4',
  },
  {
    ghid: 498293,
    login: 'jeffmo',
    name: 'Jeff Morrison',
    avatarUrl: 'https://avatars.githubusercontent.com/u/498293?v=4',
  },
  {
    ghid: 143668,
    login: 'joesepi',
    name: 'Joe Sepi',
    organisation: '@Cloudflare',
    avatarUrl: 'https://avatars.githubusercontent.com/u/143668?v=4',
  },
  {
    ghid: 1355039,
    login: 'jorydotcom',
    name: 'Jory Burson',
    organisation: '@thelinuxfoundation',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1355039?v=4',
  },
  {
    ghid: 112982,
    login: 'jridgewell',
    name: 'Justin Ridgewell',
    organisation: '@google',
    avatarUrl: 'https://avatars.githubusercontent.com/u/112982?v=4',
  },
  {
    ghid: 10776615,
    login: 'JSMonk',
    name: 'Artem Kobzar',
    avatarUrl: 'https://avatars.githubusercontent.com/u/10776615?v=4',
  },
  {
    ghid: 1523305,
    login: 'kamilogorek',
    name: 'Kamil Ogórek',
    organisation: '@supabase',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1523305?v=4',
  },
  {
    ghid: 118266,
    login: 'keithamus',
    name: 'Keith Cirkel',
    organisation: 'Mozilla',
    avatarUrl: 'https://avatars.githubusercontent.com/u/118266?v=4',
  },
  {
    ghid: 1500684,
    login: 'kentcdodds',
    name: 'Kent C. Dodds',
    organisation: '@epicweb-dev',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1500684?v=4',
  },
  {
    ghid: 6831019,
    login: 'Kingwl',
    name: 'Wenlu Wang',
    avatarUrl: 'https://avatars.githubusercontent.com/u/6831019?v=4',
  },
  {
    ghid: 60294,
    login: 'kriskowal',
    name: 'Kris Kowal',
    avatarUrl: 'https://avatars.githubusercontent.com/u/60294?v=4',
  },
  {
    ghid: 358783,
    login: 'kylebk',
    name: 'Kyle Barron-Kraus',
    organisation: 'ServiceNow',
    avatarUrl: 'https://avatars.githubusercontent.com/u/358783?v=4',
  },
  {
    ghid: 175836,
    login: 'LeaVerou',
    name: 'Lea Verou',
    avatarUrl: 'https://avatars.githubusercontent.com/u/175836?v=4',
  },
  {
    ghid: 104052,
    login: 'leeight',
    name: 'Li YuBei',
    organisation: '@Bytedance',
    avatarUrl: 'https://avatars.githubusercontent.com/u/104052?v=4',
  },
  {
    ghid: 8500303,
    login: 'legendecas',
    name: 'Chengzhong Wu',
    organisation: '@bloomberg',
    avatarUrl: 'https://avatars.githubusercontent.com/u/8500303?v=4',
  },
  {
    ghid: 301201,
    login: 'leobalter',
    name: 'Leo Balter',
    avatarUrl: 'https://avatars.githubusercontent.com/u/301201?v=4',
  },
  {
    ghid: 8118419,
    login: 'lforst',
    name: 'Luca Forstner',
    organisation: '@braintrustdata',
    avatarUrl: 'https://avatars.githubusercontent.com/u/8118419?v=4',
  },
  {
    ghid: 1158954,
    login: 'liminzhu',
    name: 'Limin Zhu',
    organisation: 'Microsoft',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1158954?v=4',
  },
  {
    ghid: 105464,
    login: 'linclark',
    name: 'Lin Clark',
    organisation: 'Fastly',
    avatarUrl: 'https://avatars.githubusercontent.com/u/105464?v=4',
  },
  {
    ghid: 19366641,
    login: 'linusg',
    name: 'Linus Groh',
    organisation: '@bloomberg',
    avatarUrl: 'https://avatars.githubusercontent.com/u/19366641?v=4',
  },
  {
    ghid: 189835,
    login: 'littledan',
    name: 'Daniel Ehrenberg',
    organisation: 'Bloomberg',
    avatarUrl: 'https://avatars.githubusercontent.com/u/189835?v=4',
  },
  {
    ghid: 45469,
    login: 'ljharb',
    name: 'Jordan Harband',
    organisation: '@socketdev @tc39',
    avatarUrl: 'https://avatars.githubusercontent.com/u/45469?v=4',
  },
  {
    ghid: 6261322,
    login: 'logaretm',
    name: 'Abdelrahman Awad',
    organisation: '@getsentry',
    avatarUrl: 'https://avatars.githubusercontent.com/u/6261322?v=4',
  },
  {
    ghid: 7829205,
    login: 'lucacasonato',
    name: 'Luca Casonato',
    avatarUrl: 'https://avatars.githubusercontent.com/u/7829205?v=4',
  },
  {
    ghid: 13161470,
    login: 'Lxxyx',
    name: 'Lxxyx',
    organisation: '@NCUHOME',
    avatarUrl: 'https://avatars.githubusercontent.com/u/13161470?v=4',
  },
  { ghid: 98569365, login: 'lyr408', name: 'ray', avatarUrl: 'https://avatars.githubusercontent.com/u/98569365?v=4' },
  {
    ghid: 6054610,
    login: 'maggiepint',
    name: 'Maggie Johnson-Pint',
    organisation: 'Stripe',
    avatarUrl: 'https://avatars.githubusercontent.com/u/6054610?v=4',
  },
  {
    ghid: 36735501,
    login: 'marco-ippolito',
    name: 'Marco Ippolito',
    organisation: '@herodevs',
    avatarUrl: 'https://avatars.githubusercontent.com/u/36735501?v=4',
  },
  {
    ghid: 81942,
    login: 'mathiasbynens',
    name: 'Mathias Bynens',
    organisation: '@Google',
    avatarUrl: 'https://avatars.githubusercontent.com/u/81942?v=4',
  },
  {
    ghid: 43753,
    login: 'mattijs',
    name: 'Mattijs Hoitink',
    avatarUrl: 'https://avatars.githubusercontent.com/u/43753?v=4',
  },
  {
    ghid: 90050,
    login: 'Me1000',
    name: 'Randy Luecke',
    organisation: 'Pax Andromeda',
    avatarUrl: 'https://avatars.githubusercontent.com/u/90050?v=4',
  },
  {
    ghid: 86499,
    login: 'mhofman',
    name: 'Mathieu Hofman',
    organisation: '@agoric',
    avatarUrl: 'https://avatars.githubusercontent.com/u/86499?v=4',
  },
  {
    ghid: 218840,
    login: 'michaelficarra',
    name: 'Michael Ficarra',
    organisation: '@f5networks',
    avatarUrl: 'https://avatars.githubusercontent.com/u/218840?v=4',
  },
  {
    ghid: 14977595,
    login: 'micheleriva',
    name: 'Michele Riva',
    organisation: 'Independent Researcher',
    avatarUrl: 'https://avatars.githubusercontent.com/u/14977595?v=4',
  },
  {
    ghid: 823846,
    login: 'mikemurry',
    name: 'Mike Murry',
    organisation: 'Evolve',
    avatarUrl: 'https://avatars.githubusercontent.com/u/823846?v=4',
  },
  {
    ghid: 368886,
    login: 'mikesamuel',
    name: 'Mike Samuel',
    avatarUrl: 'https://avatars.githubusercontent.com/u/368886?v=4',
  },
  {
    ghid: 14153763,
    login: 'milomg',
    name: 'Milo M',
    avatarUrl: 'https://avatars.githubusercontent.com/u/14153763?v=4',
  },
  {
    ghid: 2894019,
    login: 'mpcsh',
    name: 'Mark Cohen',
    organisation: '@TC39',
    avatarUrl: 'https://avatars.githubusercontent.com/u/2894019?v=4',
  },
  {
    ghid: 1153134,
    login: 'muan',
    name: 'Mu-An Chiou',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1153134?v=4',
  },
  {
    ghid: 498775,
    login: 'MylesBorins',
    name: 'Myles Borins',
    organisation: 'Snowflake',
    avatarUrl: 'https://avatars.githubusercontent.com/u/498775?v=4',
  },
  {
    ghid: 20542,
    login: 'nathanhammond',
    name: 'Nathan Hammond',
    avatarUrl: 'https://avatars.githubusercontent.com/u/20542?v=4',
  },
  {
    ghid: 395398,
    login: 'necccc',
    name: 'Szabolcs Szabolcsi-Toth',
    organisation: 'BinX Zrt',
    avatarUrl: 'https://avatars.githubusercontent.com/u/395398?v=4',
  },
  {
    ghid: 7000710,
    login: 'nicolo-ribaudo',
    name: 'Nicolò Ribaudo',
    organisation: '@babel, @igalia',
    avatarUrl: 'https://avatars.githubusercontent.com/u/7000710?v=4',
  },
  {
    ghid: 9524411,
    login: 'pd4d10',
    name: 'Rongjian Zhang',
    avatarUrl: 'https://avatars.githubusercontent.com/u/9524411?v=4',
  },
  {
    ghid: 4282439,
    login: 'phryneas',
    name: 'Lenz Weber-Tronic',
    organisation: '@apollographql',
    avatarUrl: 'https://avatars.githubusercontent.com/u/4282439?v=4',
  },
  {
    ghid: 218257,
    login: 'piscisaureus',
    name: 'Bert Belder',
    avatarUrl: 'https://avatars.githubusercontent.com/u/218257?v=4',
  },
  {
    ghid: 101547,
    login: 'pouwerkerk',
    name: 'Pieter Ouwerkerk',
    avatarUrl: 'https://avatars.githubusercontent.com/u/101547?v=4',
  },
  {
    ghid: 831623,
    login: 'rickbutton',
    name: 'Rick Button',
    organisation: '@bloomberg',
    avatarUrl: 'https://avatars.githubusercontent.com/u/831623?v=4',
  },
  {
    ghid: 2172590,
    login: 'rkirsling',
    name: 'Ross Kirsling',
    avatarUrl: 'https://avatars.githubusercontent.com/u/2172590?v=4',
  },
  {
    ghid: 1572026,
    login: 'romulocintra',
    name: 'Romulo Cintra',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1572026?v=4',
  },
  {
    ghid: 4247099,
    login: 'rossberg',
    name: 'Andreas Rossberg',
    avatarUrl: 'https://avatars.githubusercontent.com/u/4247099?v=4',
  },
  {
    ghid: 246520,
    login: 'rricard',
    name: 'Robin Ricard',
    avatarUrl: 'https://avatars.githubusercontent.com/u/246520?v=4',
  },
  {
    ghid: 967155,
    login: 'rxaviers',
    name: 'Rafael Xavier de Souza',
    organisation: 'PayPal',
    avatarUrl: 'https://avatars.githubusercontent.com/u/967155?v=4',
  },
  {
    ghid: 13121330,
    login: 'ryzokuken',
    name: 'Ujjwal Sharma',
    organisation: '@igalia',
    avatarUrl: 'https://avatars.githubusercontent.com/u/13121330?v=4',
  },
  {
    ghid: 3842474,
    login: 'septs',
    name: 'septs',
    organisation: '@NiceLabs',
    avatarUrl: 'https://avatars.githubusercontent.com/u/3842474?v=4',
  },
  {
    ghid: 105171995,
    login: 'Sharktheone',
    name: 'Shark',
    avatarUrl: 'https://avatars.githubusercontent.com/u/105171995?v=4',
  },
  {
    ghid: 5098878,
    login: 'shvaikalesh',
    name: 'Alexey Shvaika',
    avatarUrl: 'https://avatars.githubusercontent.com/u/5098878?v=4',
  },
  {
    ghid: 97331,
    login: 'slightlyoff',
    name: 'Alex Russell',
    organisation: 'Microsoft',
    avatarUrl: 'https://avatars.githubusercontent.com/u/97331?v=4',
  },
  {
    ghid: 38746192,
    login: 'smorimoto',
    name: 'Sora Morimoto',
    organisation: '@ocaml @tc39',
    avatarUrl: 'https://avatars.githubusercontent.com/u/38746192?v=4',
  },
  {
    ghid: 471400,
    login: 'southpolesteve',
    name: 'Steve Faulkner',
    organisation: '@cloudflare',
    avatarUrl: 'https://avatars.githubusercontent.com/u/471400?v=4',
  },
  {
    ghid: 855219,
    login: 'srl295',
    name: 'Steven R. Loomis',
    organisation: '@codehivetx',
    avatarUrl: 'https://avatars.githubusercontent.com/u/855219?v=4',
  },
  {
    ghid: 229881,
    login: 'styfle',
    name: 'Steven',
    organisation: '@vercel',
    avatarUrl: 'https://avatars.githubusercontent.com/u/229881?v=4',
  },
  {
    ghid: 4503403,
    login: 'sunfishcode',
    name: 'Dan Gohman',
    avatarUrl: 'https://avatars.githubusercontent.com/u/4503403?v=4',
  },
  {
    ghid: 234957,
    login: 'surma',
    name: 'Surma',
    organisation: 'Shopify',
    avatarUrl: 'https://avatars.githubusercontent.com/u/234957?v=4',
  },
  {
    ghid: 580492,
    login: 'Swatinem',
    name: 'Arpad Borsos',
    organisation: '@getsentry, @codecov',
    avatarUrl: 'https://avatars.githubusercontent.com/u/580492?v=4',
  },
  {
    ghid: 46418,
    login: 'tantek',
    name: 'Tantek Çelik',
    organisation: '@mozilla @indieweb @microformats',
    avatarUrl: 'https://avatars.githubusercontent.com/u/46418?v=4',
  },
  {
    ghid: 707073,
    login: 'tcare',
    name: 'Tom Care',
    organisation: 'Meta',
    avatarUrl: 'https://avatars.githubusercontent.com/u/707073?v=4',
  },
  {
    ghid: 1538624,
    login: 'TimothyGu',
    name: 'Timothy Gu',
    organisation: '@Stripe',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1538624?v=4',
  },
  {
    ghid: 145676,
    login: 'tomayac',
    name: 'Thomas Steiner',
    organisation: '@google Google',
    avatarUrl: 'https://avatars.githubusercontent.com/u/145676?v=4',
  },
  {
    ghid: 5657539,
    login: 'TomKopp',
    name: 'Tom Kopp',
    organisation: '@zalari',
    avatarUrl: 'https://avatars.githubusercontent.com/u/5657539?v=4',
  },
  {
    ghid: 56359,
    login: 'tschneidereit',
    name: 'Till Schneidereit',
    organisation: '@bytecodealliance @akamai',
    avatarUrl: 'https://avatars.githubusercontent.com/u/56359?v=4',
  },
  {
    ghid: 5110813,
    login: 'UlisesGascon',
    name: 'Ulises Gascón',
    organisation: '@nodesource',
    avatarUrl: 'https://avatars.githubusercontent.com/u/5110813?v=4',
  },
  {
    ghid: 3941159,
    login: 'wangyaju',
    name: 'wangyaju',
    organisation: 'HUAWEI',
    avatarUrl: 'https://avatars.githubusercontent.com/u/3941159?v=4',
  },
  { ghid: 40935, login: 'welefen', name: 'welefen', avatarUrl: 'https://avatars.githubusercontent.com/u/40935?v=4' },
  {
    ghid: 802901,
    login: 'westeezy',
    name: 'Westin Wrzesinski',
    organisation: '@Shopify',
    avatarUrl: 'https://avatars.githubusercontent.com/u/802901?v=4',
  },
  {
    ghid: 1623628,
    login: 'whymarrh',
    name: 'Whymarrh Whitby',
    organisation: '@1Password',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1623628?v=4',
  },
  {
    ghid: 1202219,
    login: 'willyelm',
    name: 'Will Medina',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1202219?v=4',
  },
  {
    ghid: 2842176,
    login: 'XadillaX',
    name: 'Khaidi Chu',
    organisation: 'ByteDance',
    avatarUrl: 'https://avatars.githubusercontent.com/u/2842176?v=4',
  },
  {
    ghid: 9291212,
    login: 'XGHeaven',
    name: 'XGHeaven',
    organisation: 'Alibaba Inc.',
    avatarUrl: 'https://avatars.githubusercontent.com/u/9291212?v=4',
  },
  {
    ghid: 1493671,
    login: 'xtuc',
    name: 'Sven Sauleau',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1493671?v=4',
  },
  {
    ghid: 1935767,
    login: 'yorkie',
    name: 'Yorkie',
    organisation: 'Rokid, Inc',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1935767?v=4',
  },
  {
    ghid: 1424844,
    login: 'younies',
    name: 'Younies Mahmoud',
    organisation: 'Google',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1424844?v=4',
  },
  { ghid: 677114, login: 'yuanyan', name: 'Y2', avatarUrl: 'https://avatars.githubusercontent.com/u/677114?v=4' },
  {
    ghid: 13394838,
    login: 'YuriTu',
    name: 'Yuri',
    organisation: '@baidu',
    avatarUrl: 'https://avatars.githubusercontent.com/u/13394838?v=4',
  },
  {
    ghid: 449986,
    login: 'zbraniecki',
    name: 'Zibi Braniecki',
    organisation: 'Amazon Lab126',
    avatarUrl: 'https://avatars.githubusercontent.com/u/449986?v=4',
  },
  {
    ghid: 754006,
    login: 'zeldajay',
    name: 'zeldajay',
    avatarUrl: 'https://avatars.githubusercontent.com/u/754006?v=4',
  },
  {
    ghid: 5995084,
    login: 'zenparsing',
    name: 'Kevin Smith',
    organisation: '@brave',
    avatarUrl: 'https://avatars.githubusercontent.com/u/5995084?v=4',
  },
] as const;
